# Generated by Django 5.2.6 on 2025-09-22 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_tag_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('swap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.swaprequest')),
            ],
        ),
    ]
