# Generated by Django 5.2.4 on 2025-08-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('size', models.CharField(default='M', max_length=10)),
                ('condition', models.CharField(default='Like New', max_length=50)),
                ('points', models.IntegerField()),
                ('rating', models.FloatField()),
                ('views', models.IntegerField(default=0)),
                ('image', models.URLField(blank=True, null=True)),
                ('posted', models.CharField(default='1 day ago', max_length=100)),
            ],
        ),
    ]
